### ISSUE TITLE
cloud-foundations.org has been lost?

### ISSUE THREAD

**Issue by ThomasHabets** [Cloud-Foundations/keymaster#112]
There are references in this repo to colud-foundations.org, but that domain has either been lost or the webserver is broken (shows a pretty empty file listing now).

Is that domain still supposed to be active? If not, probably this repo should drop references to it?

**Comment by rgooch** [comment]
https://www.cloud-foundations.org/ is alive and well.

**Comment by ThomasHabets** [comment]
Works fine now. I guess I should have waited an hour to see if it was a temporary glitch. Sorry for the noise.

**Comment by erikespinoza** [comment]
http://cloud-foundations.org/ brings up an Apache DirectoryIndex. Works fine with www.
