### ISSUE TITLE
Support expiring OTP injection when user has no active 2nd factors

### ISSUE THREAD

**Issue by rgooch** [Cloud-Foundations/keymaster#14]
Add a privileged API call to add an expiring One Time Password for a user if the user has no active 2nd factors registered. The OTP should be added to a database. When a user completes primary (username+password) authentication, the 2nd factor check will fall back to checking the database for the expiring OTP when there are no active 2nd factors registered for the user.

This may be used to streamline/automate the bootstrapping of users when they are first on-boarded and have no 2nd factor registered yet, when combined with issue #15.
This depends on issue #21.

**Comment by cviecco** [comment]
Here is my current implementation at the DB layer my idead would be to add new table on backed with 4 fields [username, code, expiration, signed jwt with [code,username,expiration] ]

However as an admin, after generation should you be able to see the code and let you figure out how to send OR have an email field where the code will be sent.

**Comment by rgooch** [comment]
Why not just save the signed JWT? Why save the unsigned values?

I think returning the OTP code is the most flexible, as it allows building more different types of workflows. When we implement full self-service, the page that guides the user can generate the OTP and then email it.

**Comment by rgooch** [comment]
Fixed long ago.
