### ISSUE TITLE
Chrome 96 - U2F being deprecated.

### ISSUE THREAD

**Issue by erikespinoza** [Cloud-Foundations/keymaster#143]
It appears that Keymaster is using the deprecated U2F plugin in Chrome. This will not work after Feb 2022. I get this warning with Chrome 96.

![image](https://user-images.githubusercontent.com/7862514/144939629-f8f8d01b-18f8-4ed5-8a14-423793bb256e.png)

Currently u2f-api.js uses the Cryptotoken extension (kmendfapggjehodndflmmgagdbamhnfd) that is built into Chrome. This is being deprecated in favor of using webauthn in future versions of Chrome and thus U2F will stop working.

**Comment by cviecco** [comment]
I am planning the following:
1. Experimental flag to allow webauthn in addition to u2f (web only)
2. Work on migrating/reusing the current u2f registrations to be signed via the webauthn api
3. Figure out client side implementation with webauthn wire/hid protocol
4. remove experimental flag.

My current plan is to have (the parallel auth with experimental backend done during this winter break).

**Comment by erikespinoza** [comment]
This was fixed
