### ISSUE TITLE
Yubikey not initially working with MacOS client

### ISSUE THREAD

**Issue by rgooch** [Cloud-Foundations/keymaster#2]
Running the MacOS Keymaster client with a Yubikey 5C nano plugged in I got this error:
`top of doU2fAuthenticate
manufacturer = "Yubico", product = "YubiKey OTP+FIDO+CCID", vid = 0x0407, pid = 0x1050
u2fhid: error reading response, read timed out`
The Yubikey did not blink.

I then plugged in a Feitian U2F token _as well_ and ran the Keymaster client again. The Feitian did not blink but the Yubikey did, so I pressed it and it worked. Before I pressed the Yubikey I pressed the (not blinking) Feitian to see what would happen and I just got OTP codes in my terminal.

I unplugged my Feitian token and tried again with just the Yubikey token and everything worked fine. I tried again and it worked.

**Comment by rgooch** [comment]
This is a daily problem. I can recover without plugging in a second token by just re-running the Keymaster client. Usually on the third attempt it works.

**Comment by prydonius** [comment]
I'm also experiencing this when running keymaster on macOS. As @rgooch says, it tends to work on the third attempt.

**Comment by prydonius** [comment]
Now I seem to be getting this error instead of the read response error:

```
top of doU2fAuthenticate
manufacturer = "Yubico", product = "YubiKey OTP+FIDO+CCID", vid = 0x0407, pid = 0x1050
hid: privilege violation
```

**Comment by cviecco** [comment]
@prydonius : if you diable the OTP on the yubikey is this still an issue? (I think this would be a workaround)

**Comment by rgooch** [comment]
I think I disabled OTP mode and still experienced the problem.

**Comment by prydonius** [comment]
I just disabled OTP, let's see if that improves anything

**Comment by prydonius** [comment]
@cviecco for the last couple of days I haven't been seeing these errors with OTP disabled. Will update this if I start seeing them again.

**Comment by prydonius** [comment]
@nikunjy have you disabled OTP? After doing so, I no longer get either of the two errors reported here.

**Comment by rgooch** [comment]
I turned off OTP a long time ago and I've seen this problem occasionally.

**Comment by cviecco** [comment]
@rgooch : what version of yubikey do you use(paste the whole -checkDevices string) and what version of MacOS?

**Comment by rgooch** [comment]
@cviecco I have MacOS Catalina 10.15.4. Output:
`manufacturer = "FT", product = "U2F KB", vid = 0x0854, pid = 0x096e
manufacturer = "Yubico", product = "YubiKey FIDO+CCID", vid = 0x0406, pid = 0x1050`

**Comment by rgooch** [comment]
Currently the incidence of this is very low for me (I have OTP disabled and am running MacOS Catalina v10.15.4). I don't see a way to debug this without being able to reproduce it on-demand.

**Comment by cviecco** [comment]
An idea.. test with using libfido2.. which is mady by yubico? https://github.com/keys-pub/go-libfido2

**Comment by cviecco** [comment]
We are using a new and different library now. I think this has been solved already. Closing this for now, if there are sill issues please feel free to reopen.
