### ISSUE TITLE
Add support for (only) Keymaster-signed X.509 authentication.

### ISSUE THREAD

**Issue by rgooch** [Cloud-Foundations/keymaster#21]
Add a new authentication type based on Keymaster-signed X.509 certificates.

This will allow calls to the Keymaster API using Keymaster-issued X.509 certificates. This is required to support issue #14.

**Comment by rgooch** [comment]
This implies changing the authentication parts of the unseal handler and the `getValidAdminRemoteUsername` function.

**Comment by cviecco** [comment]
This was mostly closed on #49.
