### ISSUE TITLE
Security Vulnerability - Missing Authentication

### ISSUE THREAD

**Issue by benmap-brex** [Cloud-Foundations/keymaster#24]
### Severity: 
High Risk

### Summary: 
Missing authentication occurs when a system does not require authentication, allowing a user to escalate privileges in the system.

### Details: 
The security team discovered the keymaster application exposed an administrative interface at https://keymaster.example.com:6920/ that did not require authentication. By browsing to the URL, an attacker can view logs containing sensitive information such as, who is authenticating, what keys the user has registered, and the challenges used during new key registration, as shown in the attached screenshot.

An attacker can use this information to perform more sophisticated attacks.

**Comment by cviecco** [comment]
Public logs should be by default off. Can you share your keymaster configuration of base: public_logs ?

**Comment by rgooch** [comment]
Yes, this was a configuration issue. I've changed. this in our deployment.

Note that I disagree that this is a high risk issue. I would rate it medium.
