### ISSUE TITLE
Provide a logout button in the 2FA tab

### ISSUE THREAD

**Issue by rgooch** [Cloud-Foundations/keymaster#3]
Currently, if someone types in a username which passes primary authentication (i.e. Okta is used for primary auth) and the user did not drop the `@company.com` part of their username, they cannot pass the 2FA step because there is no U2F token registered to `user@company.com`. The user is now in limbo, unable to retry with just `username` because they have a cookie which causes the primary authentication flow to be bypassed.

If there was a logout button during the 2FA phase, the user could recover more easily.

**Comment by cviecco** [comment]
Potential Fix see: #12

**Comment by cviecco** [comment]
Fixed by #12
