### ISSUE TITLE
Where to filter usernames?

### ISSUE THREAD

**Issue by rgooch** [Cloud-Foundations/keymaster#4]
When using Okta as the primary authentication back-end, a user can enter either `username` or `username@company.com` and the Okta API will treat them equivalently. As described in issue #3, this presents a problem during the 2FA verification, as the U2F tokens are typically registered with just `username`. If the user tries to log in with `username@company.com` the token looked will fail and thus the user will not be able to complete the 2FA challenge.

Note that the Okta configuration typically has `company` as the domain. The implicit mapping to `@company.com` is internal to Okta.

Here are some potential solutions:

1. Modify the Okta back-end to fail the login attempt if the user enters an `@`, thus forcing them to enter only `username`. This would prevent the user from getting into a limbo, half logged in state (as in issue #3), but it seems like an annoying user experience, as users have already gotten used to typing in `username@company.com`. Further, it may be challenging to present a clear message to the user explaining what went wrong

2. Add a configuration option defining a filter regexp for the username string that the user enters. This provides a good user experience, but requires the administrator to modify the configuration (which may happen after some users complain and the administrator puts in the effort to figure out what's going wrong)

3. Modify the U2F back-end to strip out the `@` and everything afterwards. Again, this gives a good user experience and doesn't require tweaking by the administrator, but would hard-code in a limitation which would prevent supporting users from multiple domains (i.e. `@company1.com` and `@company2.com`).

Overall, I think option (2) is best, as it provides a good user experience and doesn't reduce potential future flexibility.

**Comment by cviecco** [comment]
I like #2 with a default that matches the behavior described on 3. What do you think if this?

**Comment by rgooch** [comment]
Ah, so define a filter with a default that strips out the `@` and everything after it? Am I reading that correctly?

If so, I like it, because it requires no tweaking for the common case (only one domain).
