### ISSUE TITLE
Aud claim is not verified

### ISSUE THREAD

**Issue by ssuresh1750** [Cloud-Foundations/keymaster#45]
Issue

Aud claim is not verified during the jwt verification step.

Steps to reproduce

NA

Impact

The "aud" (audience) claim identifies the recipients that the JWT is intended for. Each principal intended to process the JWT MUST identify itself with a value in the audience claim. If the principal processing the claim does not identify itself with a value in the "aud" claim when this claim is present, then the JWT MUST be rejected. In this case, since the aud claim is not being verified, unintended principles might be  able to process the jwt claim.

Remediation

From looking at the code in the lines mentioned below, there is already a check for the issuer and the issuer value and the aud value are the same from (https://github.com/Cloud-Foundations/keymaster/blob/master/cmd/keymasterd/jwt.go#L57 ). Please add a check that will verify the aud claim as well. 

Code/Lines affected

https://github.com/Cloud-Foundations/keymaster/blob/69e7d716b9e539632f119b73c5352fd5845cd7fa/cmd/keymasterd/jwt.go#L77

https://github.com/Cloud-Foundations/keymaster/blob/69e7d716b9e539632f119b73c5352fd5845cd7fa/cmd/keymasterd/jwt.go#L145

**Comment by cviecco** [comment]
Thanks for the report. For the auth_claims there is only one path to generate in the code, and this this was not needed, but to be complete with the spece I created #48 . This should make this a non-issue.

**Comment by ssuresh1750** [comment]
sounds good, thank you for the quick fix! closing the issue.
