### ISSUE TITLE
Csp has unsafe-inline - style

### ISSUE THREAD

**Issue by ssuresh1750** [Cloud-Foundations/keymaster#46]
Issue

The content security policy allows unsafe-inline for style. 

Steps to reproduce

Login to keymaster (web). We will notice that the response returns the CSP header which allows unsafe inline for style. 

Impact

Allowing inline styles makes one susceptible to a the "other XSS". Cross Site Styling attacks that could end up defacing the website. Unless the other CSP rules never allow any kind of request to go to a untrusted or wildcard domain, then using a carefully crafted style rules attackers could send any information included on the page to external domains and expose or otherwise use that data maliciously against users.

Remediation

Don’t allow unsafe-inline option.

Code/Lines affected

https://github.com/Cloud-Foundations/keymaster/blob/83110259a418bde426d0fd50b2bc4a68fef3dd2d/cmd/keymasterd/app.go#L545

**Comment by cviecco** [comment]
This is mitigated for two reasons:
