### ISSUE TITLE
User list cleanup

### ISSUE THREAD

**Issue by ssuresh1750** [Cloud-Foundations/keymaster#47]
Issue

The /users/ endpoint displays a list of all the Keymaster users to any logged in user. Also, there is no cleanup of this list in the backend.

Steps to reproduce

Login to keymaster (web) Go to the /users/ endpoint. One can see the names of all the users here. 

Impact

There is no cleanup of users on keymaster backend. It would be great to add some mechanism to deactivate users on keymaster backend. Additionally, any logged in user can see a list of all keymaster users. 

Remediation

Cleanup the user list so that only valid users are maintained in the database. Additionally, this list should ideally not be visible to non-admin users.

**Comment by cviecco** [comment]
This is quite correct, and we are actually working on all of these:
1. ensuering is it only readable by admins
2. adding addition/removal by admins.

**Comment by rgooch** [comment]
Indeed. We have working prototype code that needs unittests and review.

**Comment by ssuresh1750** [comment]
okay, sounds good, thanks!

**Comment by rgooch** [comment]
Fixed in PR #57.
