### ISSUE TITLE
Keymaster incompatible with OpenSSH 8.2

### ISSUE THREAD

**Issue by eespinozans1** [Cloud-Foundations/keymaster#75]
More detail here.

https://github.com/golang/go/issues/37278

**Comment by cviecco** [comment]
Seems like the path will be to make a temporary fork of x/crypto/ssh an apply the suggested changes. 

At the api perspective I believe that the patch will be to initialy mke it an opt-in feature  by the server and also modify the rest api so the algorithm can be selected. We can probably have this ready by next weekend

**Comment by cviecco** [comment]
Back to this. The biggest issue is the lack of support for ssh-sha256 on openssh 7.x. (this includes ubuntu 16.04,ubunt 18.04, and CentOS 7). Because we dont want to be creating new sha1 certificates I believe the path forward is a follows:
1. Add support for Ed25519 certs (these are supported by ubuntu 18 and centos7)
2. Change keymaster client to request both Ed25519 and RSA certs.

**Comment by rgooch** [comment]
Which servers are you referring to in step 1 of the upgrade path?

**Comment by cviecco** [comment]
the srvers in step 1 are both the keymasterd servers (where the private key will be used), all the servers in the infrastructure (where there will be 2 keymasterd ca keys, the rsa one and the ed25519 one). For openssh 8.2+ this will allow non-patched keymasterd to soon be able to issue certs for them (step3), and for openssh < 8.1 this will allow them to be able to be authenticated with keymaster certs at step 6 (when keymasterd is then configured NOT to issue sha1 certificates).

**Comment by cviecco** [comment]
initial support for ed25519 (server side) has landed and the client side will land with https://github.com/Cloud-Foundations/keymaster/pull/107.

**Comment by cviecco** [comment]
Ed25519 Support has landed, as an optional signature type (at both client and server side). Generating the Ed25519 is still manual, but the bones of this has landed.

**Comment by eespinozans1** [comment]
ed25519 support is good enough. Resolving. Thanks.
