### ISSUE TITLE
difficulty enrolling Yubikey

### ISSUE THREAD

**Issue by jvantuyl** [Cloud-Foundations/keymaster#94]
Running newest version of Firefox (85.0.2) on MacOS Catalina (10.15.7).  Using a Yubikey 5C Nano, I recently had a great deal of trouble getting a replacement registered.

Firstly, I was getting delayed notifications when I attempted to go through the registration workflow.  While this wasn't Keymaster's fault, it didn't do a good job of indicating that the e-mail I was looking at had an old code on it.  Not entirely sure what to do here, but perhaps something involving a clear timestamp or fingerprint that should match between the e-mail and the OTP code form would be helpful.  Or perhaps some way to resend a recent code and reuse it.  The pathology of going through the registration cycle but never quite telling that you're one e-mail behind is very real and a pretty poor UX.

Once I got that right, I could never get Firefox to prompt when I attempted to register the key.  I'd click the "Register" button but it would never pop up to read the U2F key.  I was able to verify the key was installed using `ykman` and I was also able to register the key with Firefox on GitHub and Okta.  I eventually got it working with Chrome (88.0.4324.150), so it seems to be something with Firefox specifically.

**Comment by cviecco** [comment]
@jvantuyl : thanks for filing this report. It seems there are two issues here:
1. You are using the email registration workflow. But the otp valu was expired, and we need to enhance the message to indicate expiration time
2. using catalina (10.15..7) + firefox (85.0.2) the u2f registration failed. Does u2f authentication also fail also?
